export const RESOURCE_TYPES = {
  HOME: "home",
  TECHNOLOGIES: "technologies",
  SERVICES: "services",
  JOURNAL: "journal",
  CONTACT_US: "contact-us",
  CAREERS: "careers",
  ABOUT_US: "about-us",
  UI_UX: "ui-ux",
  MOBILE_APPLICATION_SERVICES: "custom-application-development-services",
  ENTERPRISE_SOFTWARE_SERVICES: "enterprise-application-development-services",
  AI_DEVELOPMENT_SERVICES: "ai-development-services",
  HIRE_AN_EXPERT: "hire-an-expert",
  DEVOPS: "devops",
  ENTERPRISE_DATA_AND_ANALYTICS: "enterprise-data-and-analytics",
} as const;
